### ISSUE TITLE
App no longer stable

### ISSUE THREAD

**Issue by willybeans** [VaultExpress/vault-express#75]
when i pull upstream master the app no longer works: 

 module.js:549
    throw err;
    ^

Error: Cannot find module 'express-session'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\William\Documents\projects\vault-express\server.js:8:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by willybeans** [comment]
didnt notice that new packages were added
